'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.239
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Android_App_Manager.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 &quot; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property x1() As String
            Get
                Return ResourceManager.GetString("x1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [特色功能]
        '''1.独创Odex模式安装，Lib模式安装，最简化安装和Push安装；
        '''2.Apk文件改名，让你的文件夹不再凌乱；
        '''3.Apk文件管理，让你管理Apk文件更容易；
        '''4.Android设备文件系统管理（暂时不支持中文文件名文件的管理）；
        '''5.Android系统第一屏和第二屏制作修改（第一屏暂时只支持HWC8650）；
        '''6.Apk程序的修改编辑，替换提取程序里的资源；
        '''7.Apk程序的反编译和编译；
        '''8.精简Apk程序里的PNG图片和OGG音频文件；
        '''9.Apk文件的重签证；
        '''10.多个Apk文件自动化安装；
        '''...
        '''
        '''[联系方式及捐款]
        '''如果你有建议或捐助我，从而开发更多功能，你可以通过以下方式
        '''QQ：1275731466
        '''E-Mail：GhostGzt@163.com
        '''中国建设银行
        '''账号：6227 0033 2159 0222 360
        '''
        '''[免责声明]
        '''   本程序只供学习使用，不可做商业用途，
        '''由本程序所衍生的一切侵害别人或组织利益，
        '''违反相关法律的行为及后果，均与本人无关,本人无承担的责任!
        '''请勿把本程序用作非法工具!
        '''由本程序所产生的后果（如误 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property x2() As String
            Get
                Return ResourceManager.GetString("x2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
